### ISSUE TITLE
Java Code Camp for Beginners

### ISSUE THREAD

**Issue by kgashok** [kgashok/orientations#35] opened 2016-12-17 06:07 UTC

**Comment by kgashok** [comment] 2016-12-17 06:27
@62ramya, @Dhivyakgisl  - I need coding mentors from industry. They have to be present full-time throughout the 2 days with their respective teams. 

Dec 30,2016 & Dec 31, 2016 - JavaCodeCamp -1 for 2nd year MCA   
Jan 6, 2017  & Jan 7, 2017   - JavaCodeCamp - 2 for 2nd year MCA 

1. Rajasekaran KITE
2. Alwin Pinakis KGCAS 
3. Bavani KITE 
4. Bharathy 
4. Dhivya 
5. Nandini 
6. Adarsh R 
7. Sheeba D
8. Saravanan R
9. Baranitharan

**Comment by kgashok** [comment] 2016-12-17 06:31
@62ramya - check with Kavitha and confirm that those she has assigned as mentors are good at Java?


| S.No | Roll  No | Reg No    | Name                | Mentor Name                |
|------|----------|-----------|---------------------|----------------------------|
| 1    | 15MCA01  | 1538M0019 | Janani K            | D.Kavitha (IIM)            |
| 2    | 16LMCA01 | 1538M7277 | Abarna,P            | D.Kavitha (IIM)            |
| 3    | 16LMCA02 | 1538M7278 | Angel A             | D.Kavitha (IIM)            |
| 4    | 16LMCA03 | 1538M7279 | Arjunan,K           | D.Kavitha (IIM)            |
| 5    | 16LMCA04 | 1538M7280 | Deepa S             | D.Kavitha (IIM)            |
| 6    | 16LMCA05 | 1538M7281 | Dharani,M           | C.Padmanabhan (IIM)        |
| 7    | 16LMCA06 | 1538M7282 | Divya S             | C.Padmanabhan (IIM)        |
| 8    | 16LMCA07 | 1538M7283 | Ethiraj,R           | C.Padmanabhan (IIM)        |
| 9    | 16LMCA08 | 1538M7284 | Ganga S             | C.Padmanabhan (IIM)        |
| 10   | 16LMCA09 | 1538M7285 | Gayathri,A          | C.Padmanabhan (IIM)        |
| 11   | 16LMCA10 | 1538M7286 | Gowtham,M           | C.Padmanabhan (IIM)        |
| 12   | 16LMCA11 | 1538M7287 | Kalaiyarasu,V       | S.Ahamed Johnsha Ali (IIM) |
| 13   | 16LMCA12 | 1538M7288 | Karthik,K G         | S.Ahamed Johnsha Ali (IIM) |
| 14   | 16LMCA13 | 1538M7289 | Kaviraj,D           | S.Ahamed Johnsha Ali (IIM) |
| 15   | 16LMCA14 | 1538M7290 | Keerthana,M         | S.Ahamed Johnsha Ali (IIM) |
| 16   | 16LMCA15 | 1538M7291 | Kowsalya,T          | S.Ahamed Johnsha Ali (IIM) |
| 17   | 16LMCA16 | 1538M7292 | Logeshwaran,P       | Sheebha (Itech)            |
| 18   | 16LMCA17 | 1538M7293 | Manish,Kumar S      | Sheebha (Itech)            |
| 19   | 16LMCA18 | 1538M7294 | Mariappan,K         | Sheebha (Itech)            |
| 20   | 16LMCA19 | 1538M7295 | Monisha,R           | Sheebha (Itech)            |
| 21   | 16LMCA20 | 1538M7296 | Muthu,Ayyampillai M | Sheebha (Itech)            |
| 22   | 16LMCA21 | 1538M7297 | Nivetha,M           | Saravanan (Itech)          |
| 23   | 16LMCA22 | 1538M7298 | Parthiban,S         | Saravanan (Itech)          |
| 24   | 16LMCA23 | 1538M7299 | Piruthivirajan,P    | Saravanan (Itech)          |
| 25   | 16LMCA24 | 1538M7300 | Poornima,S          | Saravanan (Itech)          |
| 26   | 16LMCA25 | 1538M7301 | Prabu M             | Saravanan (Itech)          |
| 27   | 16LMCA26 | 1538M7302 | Prathesha,P         | Rajasekar ( IT-Kite)       |
| 28   | 16LMCA27 | 1538M7303 | Preethi,J           | Rajasekar ( IT-Kite)       |
| 29   | 16LMCA28 | 1538M7304 | Priyanka,P          | Rajasekar ( IT-Kite)       |
| 30   | 16LMCA29 | 1538M7305 | Rajkumar,V          | Rajasekar ( IT-Kite)       |
| 31   | 16LMCA30 | 1538M7306 | Ram,Prabhu R        | Rajasekar ( IT-Kite)       |
| 32   | 16LMCA31 | 1538M7307 | Ranjith,Kumar K     | Kamala (CSC - Kite)        |
| 33   | 16LMCA32 | 1538M7308 | Sabarinivas,S       | Kamala (CSC - Kite)        |
| 34   | 16LMCA33 | 1538M7309 | Sanjay,R            | Kamala (CSC - Kite)        |
| 35   | 16LMCA34 | 1538M7310 | Sanjeevi,P          | Kamala (CSC - Kite)        |
| 36   | 16LMCA35 | 1538M7311 | Sasikumar,K         | Kamala (CSC - Kite)        |
| 37   | 16LMCA36 | 1538M7312 | Shahilambavi,B      | Suganthi (CSC-Kite)        |
| 38   | 16LMCA37 | 1538M7313 | Sivakumar,P         | Suganthi (CSC-Kite)        |
| 39   | 16LMCA38 | 1538M7314 | Sivaprakash,V       | Suganthi (CSC-Kite)        |
| 40   | 16LMCA39 | 1538M7315 | Sowbarnika,V        | Suganthi (CSC-Kite)        |
| 41   | 16LMCA40 | 1538M7316 | Srithar,S           | Suganthi (CSC-Kite)        |
| 42   | 16LMCA41 | 1538M7317 | Vinitha,A           | Niveditha (IIM)- Mphil     |
| 43   | 16LMCA42 | 1538M7318 | Vinoth,Kumar D      | Niveditha (IIM)- Mphil     |

**Comment by 62ramya** [comment] 2016-12-17 07:31
@kgashok Adarsh confirmed his availability for both sessions

**Comment by 62ramya** [comment] 2016-12-17 07:54
@kgashok  spoke with Kavitha mam, the mentors are selected as they handled the Java class before. She have informed all the mentors to solve the problems in CloudCoder before the code  camp.

We will reassign the mentors as per your suggestion.

**Comment by Dhivyakgisl** [comment] 2016-12-19 03:12
Sir, in this regard, I will speak with Rajeshwari mam today. 
I doubt my presence on both the sessions since need to start preparations for onsite travel. 
  
I will confirm the mentors list by day end. 

----- Original Message -----

**Comment by kgashok** [comment] 2016-12-19 07:39
@Dhivyakgisl  and @nandini-haricharan , 

I spoke with Rajeswari and she agreed that your participation in the code camp is essential. 
Develop a "sanity-test" for incoming fresher quality on CloudCoder. 
Discuss with me.

**Comment by Dhivyakgisl** [comment] 2016-12-19 11:34
Sir, myself and Nandini will be present for JavaCodeCamp -1 and 2 respectively. 
Will send the other mentors list from industry once confirmed. 

----- Original Message -----

**Comment by 62ramya** [comment] 2016-12-22 04:24
Tentative Mentor list 

| S.No | Roll  No | Reg No    | Name                | Mentor Name                |
|------|----------|-----------|---------------------|----------------------------|
| 1    | 15MCA01  | 1538M0019 | Janani K            | Dhivya Arun (KGISL)        |
| 2    | 16LMCA01 | 1538M7277 | Abarna,P            | Dhivya Arun (KGISL)        |
| 3    | 16LMCA02 | 1538M7278 | Angel A             | Dhivya Arun (KGISL)        |
| 4    | 16LMCA03 | 1538M7279 | Arjunan,K           | Nandini Haricharan (KGISL) |
| 5    | 16LMCA04 | 1538M7280 | Deepa S             | Nandini Haricharan (KGISL) |
| 6    | 16LMCA05 | 1538M7281 | Dharani,M           | Nandini Haricharan (KGISL) |
| 7    | 16LMCA06 | 1538M7282 | Divya S             | Dhivya Arun (KGISL)        |
| 8    | 16LMCA07 | 1538M7283 | Ethiraj,R           | Nandini Haricharan (KGISL) |
| 9    | 16LMCA08 | 1538M7284 | Ganga S             | Adarsh R                   |
| 10   | 16LMCA09 | 1538M7285 | Gayathri,A          | Adarsh R                   |
| 11   | 16LMCA10 | 1538M7286 | Gowtham,M           | Adarsh R                   |
| 12   | 16LMCA11 | 1538M7287 | Kalaiyarasu,V       | Adarsh R                   |
| 13   | 16LMCA12 | 1538M7288 | Karthik,K G         | Bharathy A                 |
| 14   | 16LMCA13 | 1538M7289 | Kaviraj,D           | Bharathy A                 |
| 15   | 16LMCA14 | 1538M7290 | Keerthana,M         | Bharathy A                 |
| 16   | 16LMCA15 | 1538M7291 | Kowsalya,T          | Bharathy A                 |
| 17   | 16LMCA16 | 1538M7292 | Logeshwaran,P       | Sheebha (Itech)            |
| 18   | 16LMCA17 | 1538M7293 | Manish,Kumar S      | Sheebha (Itech)            |
| 19   | 16LMCA18 | 1538M7294 | Mariappan,K         | Sheebha (Itech)            |
| 20   | 16LMCA19 | 1538M7295 | Monisha,R           | Sheebha (Itech)            |
| 21   | 16LMCA20 | 1538M7296 | Muthu,Ayyampillai M | Sheebha (Itech)            |
| 22   | 16LMCA21 | 1538M7297 | Nivetha,M           | Saravanan (Itech)          |
| 23   | 16LMCA22 | 1538M7298 | Parthiban,S         | Saravanan (Itech)          |
| 24   | 16LMCA23 | 1538M7299 | Piruthivirajan,P    | Saravanan (Itech)          |
| 25   | 16LMCA24 | 1538M7300 | Poornima,S          | Saravanan (Itech)          |
| 26   | 16LMCA25 | 1538M7301 | Prabu M             | Saravanan (Itech)          |
| 27   | 16LMCA26 | 1538M7302 | Prathesha,P         | Rajasekar ( IT-Kite)       |
| 28   | 16LMCA27 | 1538M7303 | Preethi,J           | Rajasekar ( IT-Kite)       |
| 29   | 16LMCA28 | 1538M7304 | Priyanka,P          | Rajasekar ( IT-Kite)       |
| 30   | 16LMCA29 | 1538M7305 | Rajkumar,V          | Rajasekar ( IT-Kite)       |
| 31   | 16LMCA30 | 1538M7306 | Ram,Prabhu R        | Rajasekar ( IT-Kite)       |
| 32   | 16LMCA31 | 1538M7307 | Ranjith,Kumar K     | Baranitharan               |
| 33   | 16LMCA32 | 1538M7308 | Sabarinivas,S       | Baranitharan               |
| 34   | 16LMCA33 | 1538M7309 | Sanjay,R            | Baranitharan               |
| 35   | 16LMCA34 | 1538M7310 | Sanjeevi,P          | Baranitharan               |
| 36   | 16LMCA35 | 1538M7311 | Sasikumar,K         | Bavani KITE                |
| 37   | 16LMCA36 | 1538M7312 | Shahilambavi,B      | Bavani KITE                |
| 38   | 16LMCA37 | 1538M7313 | Sivakumar,P         | Bavani KITE                |
| 39   | 16LMCA38 | 1538M7314 | Sivaprakash,V       | Bavani KITE                |
| 40   | 16LMCA39 | 1538M7315 | Sowbarnika,V        | Alwin Pinakis KGCAS        |
| 41   | 16LMCA40 | 1538M7316 | Srithar,S           | Alwin Pinakis KGCAS        |
| 42   | 16LMCA41 | 1538M7317 | Vinitha,A           | Alwin Pinakis KGCAS        |
| 43   | 16LMCA42 | 1538M7318 | Vinoth,Kumar D      | Alwin Pinakis KGCAS        |

**Closed as completed** 2017-01-09 13:20 UTC
